parameters:
#    madesst_cs_rest.example.class: Madesst\CSRestBundle\Example

services:
#    madesst_cs_rest.example:
#        class: %madesst_cs_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
